# Generated by Django 3.1.5 on 2021-02-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_auto_20210220_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardratemodel',
            options={'managed': True, 'verbose_name': 'cardRateModel', 'verbose_name_plural': 'cardRateModels'},
        ),
        migrations.AlterModelTable(
            name='cardratemodel',
            table='card_rate',
        ),
    ]
