# Generated by Django 3.1.5 on 2021-02-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0009_auto_20210222_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardratemodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='cardratemodel',
            table=None,
        ),
    ]
