# Generated by Django 3.1.5 on 2021-02-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_cardratemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardratemodel',
            old_name='card_rate',
            new_name='rate',
        ),
    ]
