# Generated by Django 3.1.5 on 2021-02-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_auto_20210221_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardratemodel',
            name='rate',
            field=models.CharField(max_length=30),
        ),
    ]
