# Generated by Django 3.1.5 on 2021-02-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_remove_tradecardtypemodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardratemodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
