# Generated by Django 3.1.5 on 2021-02-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0018_auto_20210227_1420'),
        ('adminPanel', '0012_auto_20210228_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardratemodel',
            name='rate',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TradeCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='images/TradeComment')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradersPanel.maintrademodel')),
            ],
        ),
    ]
