# Generated by Django 3.1.5 on 2021-02-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0014_declinecommentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeclineCommentModel',
        ),
    ]
