# Generated by Django 3.1.5 on 2021-03-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0018_auto_20210227_1420'),
        ('adminPanel', '0016_auto_20210302_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentimgmodel',
            name='comment_line',
        ),
        migrations.AddField(
            model_name='commentimgmodel',
            name='trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tradersPanel.maintrademodel'),
            preserve_default=False,
        ),
    ]
