# Generated by Django 3.1.5 on 2021-03-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0017_auto_20210302_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentimgmodel',
            old_name='profile_img',
            new_name='comment_img',
        ),
    ]
