# Generated by Django 3.1.5 on 2021-01-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0003_sendfeedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendfeedbackmodel',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sendfeedbackmodel',
            name='feedbackText',
            field=models.CharField(max_length=254),
        ),
    ]
