# Generated by Django 3.1.5 on 2021-01-22 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0004_auto_20210122_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendfeedbackmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
