# Generated by Django 2.1.7 on 2021-02-08 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminPanel', '0001_initial'),
        ('tradersPanel', '0006_profiledetails_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Success'), ('3', 'Failed')], max_length=255)),
                ('trade_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminPanel.TradeCardTypeModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TradeModel',
                'verbose_name_plural': 'TradeModels',
                'db_table': 'trades',
                'managed': True,
            },
        ),
    ]
