# Generated by Django 2.1.7 on 2021-02-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0007_trademodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='image',
            field=models.ImageField(null=True, upload_to='trade_card'),
        ),
    ]
