# Generated by Django 2.1.7 on 2021-02-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0008_trademodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Success'), ('3', 'Failed')], default='1', max_length=10),
        ),
    ]
