# Generated by Django 3.1.5 on 2021-02-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0013_auto_20210226_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='trade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_lines', to='tradersPanel.maintrademodel'),
        ),
    ]
