# Generated by Django 3.1.5 on 2021-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0017_maintrademodel_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='trade_line',
            field=models.CharField(max_length=200),
        ),
    ]
