# Generated by Django 3.1.5 on 2021-03-11 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0018_auto_20210227_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='referral_code',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
