# Generated by Django 3.1.5 on 2021-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0019_profiledetails_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='referred_by',
            field=models.CharField(default=33243, max_length=255),
            preserve_default=False,
        ),
    ]
