# Generated by Django 3.1.5 on 2021-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0020_profiledetails_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
