# Generated by Django 3.1.5 on 2021-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0023_profiledetails_referral_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='referral_point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
