# Generated by Django 3.1.5 on 2021-03-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradersPanel', '0024_auto_20210311_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='referral_point',
            field=models.IntegerField(blank=True, default=33),
            preserve_default=False,
        ),
    ]
